[package]
name = "smol-kv"
version = "0.1.0"
authors = ["Uk <ukchukundah@gmail.com>", "mpw <x@mpw.sh>"]
edition = "2021"

[dependencies]
bytes = "1.5.0"
env_logger = "0.10.0"
serde_json = "1.0.104"
rocksdb = { version = "0.21.0", features=["multi-threaded-cf"]}
actix-web = "4.3.1"
log = "0.4.19"
