[package]
name = "smol-kv"
version = "0.2.1"
authors = ["mpw <x@mpw.sh>"]
edition = "2021"

[dependencies]
#rocksdb-client = { git = "https://github.com/mpwsh/rocksdb-client", version = "0.1.9" }
rocksdb-client = { path = "../rocksdb-client"}
sha1 = "0.10.6"
bytes = "1.5.0"
env_logger = "0.11.1"
serde_json = "1.0.104"
thiserror = "1.0.61"
serde = { version = "1.0.203", features = ["derive"] }
actix-web = "4.3.1"
log = "0.4.22"
rand = "0.8"
hex = "0.4.3"
num_cpus = "1.16.0"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
