[package]
name = "smol-kv"
version = "0.1.0"
authors = ["Uk <ukchukundah@gmail.com>", "mpw <x@mpw.sh>"]
edition = "2021"

[dependencies]
bytes = "1.2.1"
env_logger = "0.9.1"
serde_json = "1.0.48"
rocksdb = { version = "0.19.0", features=["multi-threaded-cf"]}
actix-web = "4.2.1"
log = "0.4.17"
