[toolchain]
channel = "1.77.2"
components = [
  "cargo",
  "clippy",
  "rust-analysis",
  "rust-analyzer",
  "rust-docs",
  "rust-src",
  "rust-std",
  "rustc",
  "rustfmt",
]
profile = "minimal"

# vim:set ft=toml:
